# Camera Parameters
Camera.fx: 467.74270306499267
Camera.fy: 467.74270306499267
Camera.cx: 320.5
Camera.cy: 240.5

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0

Camera.width: 640
Camera.height: 480
Camera.fps: 30

Camera.RGB: 1
Camera.type: "PinHole"

# IMU Parameters
IMU.AccelerometerBias:
  x: 0.0
  y: 0.0
  z: 0.0
IMU.GyroscopeBias:
  x: 0.0
  y: 0.0
  z: 0.0

IMU.AccelerometerScale:
  x: 1.0
  y: 1.0
  z: 1.0
IMU.GyroscopeScale:
  x: 1.0
  y: 1.0
  z: 1.0

IMU.NoiseDensity:
  accelerometer: 0.0
  gyroscope: 0.0

IMU.RandomWalk:
  accelerometer: 0.0
  gyroscope: 0.0

# Viewer Parameters
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 1
Viewer.ViewpointY: -1
Viewer.ViewpointZ: -0.5
Viewer.ViewpointF: 500

# ORB Parameters
ORBextractor.nFeatures: 2500
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7